In [262]:
import pandas as pd
df=pd.read_csv('Product_sales.csv')
df

ProductKey  OrderQuantity  ProductCate_Key CategoryName     cost  \
0             529              2                4  Accessories     1.49   
1             214              1                4  Accessories    13.09   
2             540              1                4  Accessories    12.19   
3             529              2                4  Accessories     1.49   
4             377              1                1        Bikes  1320.68   
...           ...            ...              ...          ...      ...   
29476         477              2                4  Accessories     1.87   
29477         479              1                4  Accessories     3.36   
29478         606              1                1        Bikes   343.65   
29479         480              2                4  Accessories     0.86   
29480         538              2                4  Accessories     8.04   

         price  total_price  total_cost  revenue  
0         3.99         7.98        2.98     5.00  
1        34.99        34.99       13.09    21.90  
2        32.60        32.60       12.19    20.41  
3         3.99         7.98        2.98     5.00  
4      2181.56      2181.56     1320.68   860.88  
...        ...          ...         ...      ...  
29476     4.99         9.98        3.73     6.25  
29477     8.99         8.99        3.36     5.63  
29478   539.99       539.99      343.65   196.34  
29479     2.29         4.58        1.71     2.87  
29480    21.49        42.98       16.07    26.91  

[29481 rows x 9 columns]

In [263]:
df.describe()

ProductKey  OrderQuantity  ProductCate_Key          cost  \
count  29481.000000   29481.000000     29481.000000  29481.000000   
mean     446.461382       1.537058         3.255826    177.302854   
std      121.027611       0.617249         1.161144    386.804583   
min      214.000000       1.000000         1.000000      0.860000   
25%      381.000000       1.000000         3.000000      1.870000   
50%      480.000000       1.000000         4.000000      9.710000   
75%      530.000000       2.000000         4.000000     31.720000   
max      606.000000       3.000000         4.000000   1481.940000   

              price   total_price    total_cost       revenue  
count  29481.000000  29481.000000  29481.000000  29481.000000  
mean     305.610741    311.571768    179.654962    131.917313  
std      655.066681    652.519183    385.786461    269.591216  
min        2.290000      2.290000      0.860000      1.430000  
25%        4.990000     11.970000      5.600000      6.250000  
50%       24.990000     34.990000     13.090000     21.620000  
75%       53.990000     59.980000     31.720000     37.550000  
max     2384.070000   2384.070000   1481.940000    953.560000

In [264]:
df.columns

Index(['ProductKey', 'OrderQuantity', 'ProductCate_Key', 'CategoryName',
       'cost', 'price', 'total_price', 'total_cost', 'revenue'],
      dtype='object')

In [265]:
df.shape

(29481, 9)

In [266]:
df.head()

ProductKey  OrderQuantity  ProductCate_Key CategoryName     cost    price  \
0         529              2                4  Accessories     1.49     3.99   
1         214              1                4  Accessories    13.09    34.99   
2         540              1                4  Accessories    12.19    32.60   
3         529              2                4  Accessories     1.49     3.99   
4         377              1                1        Bikes  1320.68  2181.56   

   total_price  total_cost  revenue  
0         7.98        2.98     5.00  
1        34.99       13.09    21.90  
2        32.60       12.19    20.41  
3         7.98        2.98     5.00  
4      2181.56     1320.68   860.88

In [ ]:
df[""].mean()

In [267]:
class_1=df[['CategoryName','revenue']]
class_1
lst_1=class_1.values.tolist()
t1=[(x,y)for x, y in lst_1]


for x, y in enumerate(t1):
    if y[0]=='Accessories'and y[1]<14.00:
        df.loc[x,'Level']='low'
    if y[0]=='Accessories'and 14.00<=y[1]<=17.00:
        df.loc[x,'Level']='medium'
    if y[0]=='Accessories'and y[1]>17.00:
        df.loc[x,'Level']='high'
    if y[0]=='Bikes'and y[1]<550.00:  
        df.loc[x,'Level']='low'
    if y[0]=='Bikes'and 550.00<=y[1]<=650.00:
        df.loc[x,'Level']='medium'
    if y[0]=='Bikes'and y[1]>650.00:
        df.loc[x,'Level']='high'
    if y[0]=='Clothing'and y[1]<14.00:  
        df.loc[x,'Level']='low'
    if y[0]=='Clothing'and 14.00<=y[1]<=22.00:
        df.loc[x,'Level']='medium'
    if y[0]=='Clothing'and y[1]>22.00:
        df.loc[x,'Level']='high'
 

df


# df1=df.drop('CategoryName', axis=1)
# df1
# print(df1['Level'].unique())
# print(df['CategoryName'].unique())

ProductKey  OrderQuantity  ProductCate_Key CategoryName     cost  \
0             529              2                4  Accessories     1.49   
1             214              1                4  Accessories    13.09   
2             540              1                4  Accessories    12.19   
3             529              2                4  Accessories     1.49   
4             377              1                1        Bikes  1320.68   
...           ...            ...              ...          ...      ...   
29476         477              2                4  Accessories     1.87   
29477         479              1                4  Accessories     3.36   
29478         606              1                1        Bikes   343.65   
29479         480              2                4  Accessories     0.86   
29480         538              2                4  Accessories     8.04   

         price  total_price  total_cost  revenue Level  
0         3.99         7.98        2.98     5.00   low  
1        34.99        34.99       13.09    21.90  high  
2        32.60        32.60       12.19    20.41  high  
3         3.99         7.98        2.98     5.00   low  
4      2181.56      2181.56     1320.68   860.88  high  
...        ...          ...         ...      ...   ...  
29476     4.99         9.98        3.73     6.25   low  
29477     8.99         8.99        3.36     5.63   low  
29478   539.99       539.99      343.65   196.34   low  
29479     2.29         4.58        1.71     2.87   low  
29480    21.49        42.98       16.07    26.91  high  

[29481 rows x 10 columns]

In [268]:
# df.Level[df.Level == 'low'] = 0
# df.Level[df.Level == 'medium'] = 1
# df.Level[df.Level=='high']=2
# df

In [260]:
# items=df['CategoryName'].unique()   

# item1=df[df['CategoryName']=="Accessories"]
# item1

In [269]:
feature_names = ['ProductCate_Key','']
X = df[feature_names]## feature
y = df['Level']##label


In [228]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(22110, 2) (22110,)
(7371, 2) (7371,)


In [229]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))


Accuracy of Logistic regression classifier on training set: 0.83
Accuracy of Logistic regression classifier on test set: 0.82


C:\Users\wingy\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [230]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 1.00


In [232]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 1.00
Accuracy of K-NN classifier on test set: 1.00


In [233]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

Accuracy of LDA classifier on training set: 0.89
Accuracy of LDA classifier on test set: 0.89


In [234]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.53
Accuracy of GNB classifier on test set: 0.54


In [235]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Accuracy of SVM classifier on training set: 0.96
Accuracy of SVM classifier on test set: 0.96


In [236]:
## KNN model:

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[3175    0    0]
 [   0 3757    0]
 [   0    0  439]]
              precision    recall  f1-score   support

        high       1.00      1.00      1.00      3175
         low       1.00      1.00      1.00      3757
      medium       1.00      1.00      1.00       439

    accuracy                           1.00      7371
   macro avg       1.00      1.00      1.00      7371
weighted avg       1.00      1.00      1.00      7371



In [237]:
## SVM model
pred1 = svm.predict(X_test)
print(confusion_matrix(y_test, pred1))
print(classification_report(y_test, pred1))

[[3175    0    0]
 [   0 3757    0]
 [  40  257  142]]
              precision    recall  f1-score   support

        high       0.99      1.00      0.99      3175
         low       0.94      1.00      0.97      3757
      medium       1.00      0.32      0.49       439

    accuracy                           0.96      7371
   macro avg       0.97      0.77      0.82      7371
weighted avg       0.96      0.96      0.95      7371



In [238]:
##gaussian naive bayes model
pred2 = gnb.predict(X_test)
print(confusion_matrix(y_test, pred2))
print(classification_report(y_test, pred2))

[[ 627 2548    0]
 [ 424 3333    0]
 [ 142  297    0]]
              precision    recall  f1-score   support

        high       0.53      0.20      0.29      3175
         low       0.54      0.89      0.67      3757
      medium       0.00      0.00      0.00       439

    accuracy                           0.54      7371
   macro avg       0.36      0.36      0.32      7371
weighted avg       0.50      0.54      0.47      7371



C:\Users\wingy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [239]:
## logistic regression model
pred3 = logreg.predict(X_test)
print(confusion_matrix(y_test, pred3))
print(classification_report(y_test, pred3))

[[2775  400    0]
 [ 472 3285    0]
 [ 210  229    0]]
              precision    recall  f1-score   support

        high       0.80      0.87      0.84      3175
         low       0.84      0.87      0.86      3757
      medium       0.00      0.00      0.00       439

    accuracy                           0.82      7371
   macro avg       0.55      0.58      0.56      7371
weighted avg       0.77      0.82      0.80      7371



C:\Users\wingy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [240]:
## LDA model
pred4 = lda.predict(X_test)
print(confusion_matrix(y_test, pred4))
print(classification_report(y_test, pred4))

[[2775  400    0]
 [   0 3757    0]
 [ 142  297    0]]
              precision    recall  f1-score   support

        high       0.95      0.87      0.91      3175
         low       0.84      1.00      0.92      3757
      medium       0.00      0.00      0.00       439

    accuracy                           0.89      7371
   macro avg       0.60      0.62      0.61      7371
weighted avg       0.84      0.89      0.86      7371



C:\Users\wingy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [241]:
## Decision Tree Model
pred5 = clf.predict(X_test)
print(confusion_matrix(y_test, pred5))
print(classification_report(y_test, pred5))

[[3175    0    0]
 [   0 3757    0]
 [   0    0  439]]
              precision    recall  f1-score   support

        high       1.00      1.00      1.00      3175
         low       1.00      1.00      1.00      3757
      medium       1.00      1.00      1.00       439

    accuracy                           1.00      7371
   macro avg       1.00      1.00      1.00      7371
weighted avg       1.00      1.00      1.00      7371



In [242]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [243]:
y_pred = classifier.predict(X_test)

In [244]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df.head(20)

Actual Predicted
3403      low       low
20819    high      high
18903     low       low
13826     low       low
15129    high      high
20264     low       low
26153    high      high
24546  medium    medium
8103     high      high
24607    high      high
14537    high      high
14146     low       low
26853    high      high
9634      low       low
14890  medium    medium
4938      low       low
28875    high      high
17189     low       low
20253    high      high
26828    high      high

In [250]:
new_input =[[4,20]]
print(new_input)

[[4, 20]]


In [251]:
y_pred = classifier.predict(new_input)
print(new_input, y_pred)

[[4, 20]] ['high']


# DT regression

In [1]:
import pandas as pd
df_r=pd.read_csv('Product_sales.csv')
df_r

ProductKey  OrderQuantity  ProductCate_Key CategoryName     cost  \
0             529              2                4  Accessories     1.49   
1             214              1                4  Accessories    13.09   
2             540              1                4  Accessories    12.19   
3             529              2                4  Accessories     1.49   
4             377              1                1        Bikes  1320.68   
...           ...            ...              ...          ...      ...   
29476         477              2                4  Accessories     1.87   
29477         479              1                4  Accessories     3.36   
29478         606              1                1        Bikes   343.65   
29479         480              2                4  Accessories     0.86   
29480         538              2                4  Accessories     8.04   

         price  total_price  total_cost  revenue  
0         3.99         7.98        2.98     5.00  
1        34.99        34.99       13.09    21.90  
2        32.60        32.60       12.19    20.41  
3         3.99         7.98        2.98     5.00  
4      2181.56      2181.56     1320.68   860.88  
...        ...          ...         ...      ...  
29476     4.99         9.98        3.73     6.25  
29477     8.99         8.99        3.36     5.63  
29478   539.99       539.99      343.65   196.34  
29479     2.29         4.58        1.71     2.87  
29480    21.49        42.98       16.07    26.91  

[29481 rows x 9 columns]

In [2]:
df1=df_r.drop(['CategoryName'], axis=1)
df1
# X = df_r.drop('CaategoryName' axis=1)
# y = df_r['total_cost']

ProductKey  OrderQuantity  ProductCate_Key     cost    price  \
0             529              2                4     1.49     3.99   
1             214              1                4    13.09    34.99   
2             540              1                4    12.19    32.60   
3             529              2                4     1.49     3.99   
4             377              1                1  1320.68  2181.56   
...           ...            ...              ...      ...      ...   
29476         477              2                4     1.87     4.99   
29477         479              1                4     3.36     8.99   
29478         606              1                1   343.65   539.99   
29479         480              2                4     0.86     2.29   
29480         538              2                4     8.04    21.49   

       total_price  total_cost  revenue  
0             7.98        2.98     5.00  
1            34.99       13.09    21.90  
2            32.60       12.19    20.41  
3             7.98        2.98     5.00  
4          2181.56     1320.68   860.88  
...            ...         ...      ...  
29476         9.98        3.73     6.25  
29477         8.99        3.36     5.63  
29478       539.99      343.65   196.34  
29479         4.58        1.71     2.87  
29480        42.98       16.07    26.91  

[29481 rows x 8 columns]

In [16]:

X = df1[['ProductCate_Key','OrderQuantity','cost','price']]
y = df1['revenue']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [19]:
y_pred = regressor.predict(X_test)

In [21]:
df2=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df2

Actual  Predicted
3403     5.00       5.00
20819   34.42      34.42
18903    5.00       5.00
13826    6.25       6.25
15129   43.81      43.81
...       ...        ...
15155  902.13     902.13
6935     6.25       6.25
20432  943.29     943.29
19049    9.37       9.37
14772    6.25       6.25

[5897 rows x 2 columns]

In [22]:
from sklearn import metrics
import numpy as np
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5.557201110830383e-13
Mean Squared Error: 2.034680522180612e-24
Root Mean Squared Error: 1.4264222804557604e-12


In [25]:
y_pred = regressor.predict(np.array([3,2,4.5,6.00]).reshape(1,4))
### category:3, qty is 2, cost is 4.5, price is 6.00, revenue is 6.25. shape(1,4)--> one observation and 
##3 features you input. 
print(y_pred)

[6.25]
